### ISSUE TITLE
createDiabetes() URL error

### ISSUE THREAD

**Issue by MikelBa** [jkrijthe/createdatasets#1]
I tried to run the `createDiabetes()` function and it gave me the next error:
```
trying URL 'http://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data'
Error in download.file(input, tmpFile, method = method, mode = "wb", quiet = !showProgress) : 
  cannot open URL 'http://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data'
In addition: Warning message:
In download.file(input, tmpFile, method = method, mode = "wb", quiet = !showProgress) :
  cannot open URL 'http://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data': HTTP status was '404 Not Found'
```
It seems that the file `pima-indians-diabetes.data` is no longer available. However, in [Kaggle](https://www.kaggle.com/uciml/pima-indians-diabetes-database) it seems that the dataset is available. Would it be possible to use this dataset?

**Comment by jkrijthe** [comment]
Thanks for reporting this. It is unclear to me why the dataset was removed, and whether the permission issues mentioned also apply to using the dataset if it is obtained from other sources (like Kaggle).

**Comment by MikelBa** [comment]
Thank you for your response!
